import 'dart:ui';

import 'growth_island_config_models.dart';

class GrowthIslandConfigs {
  GrowthIslandConfigs._();

  static const zones = <ZoneConfig>[
    ZoneConfig(
      id: 'CenterZone',
      name: 'Center',
      priority: 50,
      bounds: Rect.fromLTWH(0.36, 0.50, 0.28, 0.10),
      allowedBuildings: [
        'starter_stone',
        'growth_house',
        'growth_house_lv2',
        'memory_fountain',
        'growth_clocktower',
        'growth_academy',
        'lighthouse_base',
        'lighthouse',
      ],
      allowedDecorations: const [],
    ),
    ZoneConfig(
      id: 'EmotionZone',
      name: 'Emotion',
      priority: 30,
      bounds: Rect.fromLTWH(0.34, 0.52, 0.32, 0.10),
      allowedBuildings: ['emotion_windchime', 'habit_flowerbed', 'quiet_tent'],
      allowedDecorations: const [],
    ),
    ZoneConfig(
      id: 'MemoryZone',
      name: 'Memory',
      priority: 20,
      bounds: Rect.fromLTWH(0.20, 0.48, 0.22, 0.12),
      allowedBuildings: [
        'record_shed',
        'memory_mailbox',
        'memory_gallery',
      ],
      allowedDecorations: const [],
    ),
    ZoneConfig(
      id: 'KnowledgeZone',
      name: 'Knowledge',
      priority: 20,
      bounds: Rect.fromLTWH(0.58, 0.48, 0.22, 0.12),
      allowedBuildings: [
        'lighthouse_base',
        'story_plaza',
        'library_seed',
      ],
      allowedDecorations: const [],
    ),
    ZoneConfig(
      id: 'FutureZone',
      name: 'Future',
      priority: 10,
      bounds: Rect.fromLTWH(0.34, 0.46, 0.32, 0.10),
      allowedBuildings: ['lighthouse', 'dream_observatory'],
      allowedDecorations: const [],
    ),
    ZoneConfig(
      id: 'HarborZone',
      name: 'Harbor',
      priority: 40,
      bounds: Rect.fromLTWH(0.24, 0.52, 0.20, 0.10),
      allowedBuildings: ['harbor_pier', 'companion_plaza'],
      allowedDecorations: const [],
    ),
  ];

  static const buildings = <BuildingConfig>[
    BuildingConfig(
      id: 'starter_stone',
      name: 'Starter Stone',
      type: 'stone',
      unlockLevel: 3,
      zone: 'CenterZone',
      position: Offset(0.28, 0.64),
      size: Offset(0.12, 0.11),
      sprite: 'buildings/starter_stone.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'record_shed',
      name: 'Record Shed',
      type: 'shed',
      unlockLevel: 5,
      zone: 'MemoryZone',
      position: Offset(0.66, 0.54),
      size: Offset(0.22, 0.19),
      sprite: 'buildings/record_shed.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'memory_mailbox',
      name: 'Memory Mailbox',
      type: 'mailbox',
      unlockLevel: 7,
      zone: 'MemoryZone',
      position: Offset(0.72, 0.58),
      size: Offset(0.14, 0.14),
      sprite: 'buildings/memory_mailbox.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_house',
      name: 'Growth House',
      type: 'house',
      unlockLevel: 9,
      zone: 'CenterZone',
      position: Offset(0.62, 0.50),
      size: Offset(0.30, 0.26),
      sprite: 'buildings/growth_house.png',
      animation: 'warm_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_house_lv2',
      name: 'Growth House Lv2',
      type: 'house',
      unlockLevel: 20,
      zone: 'CenterZone',
      position: Offset(0.62, 0.50),
      size: Offset(0.34, 0.30),
      sprite: 'buildings/growth_house_lv2.png',
      animation: 'warm_idle',
      interactionType: 'inspect',
      upgradeLevel: 2,
    ),
    BuildingConfig(
      id: 'harbor_pier',
      name: 'Harbor Pier',
      type: 'pier',
      unlockLevel: 11,
      zone: 'HarborZone',
      position: Offset(0.20, 0.61),
      size: Offset(0.26, 0.16),
      sprite: 'buildings/harbor_pier.png',
      animation: 'water_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'emotion_windchime',
      name: 'Emotion Windchime',
      type: 'windchime',
      unlockLevel: 13,
      zone: 'EmotionZone',
      position: Offset(0.42, 0.66),
      size: Offset(0.16, 0.20),
      sprite: 'buildings/emotion_windchime.png',
      animation: 'sway',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'habit_flowerbed',
      name: 'Habit Flowerbed',
      type: 'flowerbed',
      unlockLevel: 15,
      zone: 'EmotionZone',
      position: Offset(0.58, 0.66),
      size: Offset(0.22, 0.13),
      sprite: 'buildings/habit_flowerbed.png',
      animation: 'bloom',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'quiet_tent',
      name: 'Quiet Tent',
      type: 'tent',
      unlockLevel: 17,
      zone: 'EmotionZone',
      position: Offset(0.50, 0.70),
      size: Offset(0.22, 0.17),
      sprite: 'buildings/quiet_tent.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'lighthouse_base',
      name: 'Lighthouse Base',
      type: 'lighthouse_base',
      unlockLevel: 11,
      zone: 'CenterZone',
      position: Offset(0.50, 0.36),
      size: Offset(0.20, 0.20),
      sprite: 'buildings/lighthouse_base.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'story_plaza',
      name: 'Story Plaza',
      type: 'plaza',
      unlockLevel: 12,
      zone: 'KnowledgeZone',
      position: Offset(0.66, 0.56),
      size: Offset(0.26, 0.16),
      sprite: 'buildings/story_plaza.png',
      animation: 'spark',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'memory_fountain',
      name: 'Memory Fountain',
      type: 'fountain',
      unlockLevel: 13,
      zone: 'CenterZone',
      position: Offset(0.50, 0.50),
      size: Offset(0.24, 0.20),
      sprite: 'buildings/memory_fountain.png',
      animation: 'water_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'library_seed',
      name: 'Library Seed',
      type: 'library',
      unlockLevel: 14,
      zone: 'KnowledgeZone',
      position: Offset(0.28, 0.48),
      size: Offset(0.26, 0.21),
      sprite: 'buildings/library_seed.png',
      animation: 'page_float',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_clocktower',
      name: 'Growth Clocktower',
      type: 'clocktower',
      unlockLevel: 15,
      zone: 'CenterZone',
      position: Offset(0.58, 0.38),
      size: Offset(0.22, 0.32),
      sprite: 'buildings/growth_clocktower.png',
      animation: 'clock_light',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'lighthouse',
      name: 'Lighthouse',
      type: 'lighthouse',
      unlockLevel: 16,
      zone: 'CenterZone',
      position: Offset(0.76, 0.46),
      size: Offset(0.20, 0.32),
      sprite: 'buildings/lighthouse.png',
      animation: 'beam',
      interactionType: 'inspect',
      upgradeLevel: 2,
    ),
    BuildingConfig(
      id: 'companion_plaza',
      name: 'Companion Plaza',
      type: 'plaza',
      unlockLevel: 17,
      zone: 'HarborZone',
      position: Offset(0.34, 0.70),
      size: Offset(0.26, 0.16),
      sprite: 'buildings/companion_plaza.png',
      animation: 'life_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'memory_gallery',
      name: 'Memory Gallery',
      type: 'gallery',
      unlockLevel: 18,
      zone: 'MemoryZone',
      position: Offset(0.20, 0.44),
      size: Offset(0.28, 0.21),
      sprite: 'buildings/memory_gallery.png',
      animation: 'glow',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'dream_observatory',
      name: 'Dream Observatory',
      type: 'observatory',
      unlockLevel: 19,
      zone: 'FutureZone',
      position: Offset(0.42, 0.27),
      size: Offset(0.26, 0.23),
      sprite: 'buildings/dream_observatory.png',
      animation: 'glimmer',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_academy',
      name: 'Growth Academy',
      type: 'academy',
      unlockLevel: 20,
      zone: 'CenterZone',
      position: Offset(0.50, 0.40),
      size: Offset(0.38, 0.28),
      sprite: 'buildings/growth_academy.png',
      animation: 'complete_aura',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
  ];


  static const paths = <PathConfig>[
    PathConfig(
        id: 'path_center_seed',
        unlockLevel: 2,
        startNode: 'starter_stone',
        endNode: 'starter_stone',
        pathType: 'footprint',
        width: 4),
    PathConfig(
        id: 'path_center_memory',
        unlockLevel: 3,
        startNode: 'starter_stone',
        endNode: 'record_shed',
        pathType: 'dirt',
        width: 5),
    PathConfig(
        id: 'path_memory_loop',
        unlockLevel: 4,
        startNode: 'record_shed',
        endNode: 'memory_mailbox',
        pathType: 'dirt',
        width: 4),
    PathConfig(
        id: 'path_house_core',
        unlockLevel: 5,
        startNode: 'starter_stone',
        endNode: 'growth_house',
        pathType: 'stone',
        width: 6),
    PathConfig(
        id: 'path_house_harbor',
        unlockLevel: 6,
        startNode: 'growth_house',
        endNode: 'harbor_pier',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_emotion_branch',
        unlockLevel: 7,
        startNode: 'growth_house',
        endNode: 'emotion_windchime',
        pathType: 'dirt',
        width: 4),
    PathConfig(
        id: 'path_flowerbed',
        unlockLevel: 8,
        startNode: 'emotion_windchime',
        endNode: 'habit_flowerbed',
        pathType: 'flower',
        width: 4),
    PathConfig(
        id: 'path_tent',
        unlockLevel: 9,
        startNode: 'habit_flowerbed',
        endNode: 'quiet_tent',
        pathType: 'dirt',
        width: 4),
    PathConfig(
        id: 'path_ring_1',
        unlockLevel: 10,
        startNode: 'harbor_pier',
        endNode: 'quiet_tent',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_center_knowledge',
        unlockLevel: 11,
        startNode: 'growth_house',
        endNode: 'lighthouse_base',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_plaza_axis',
        unlockLevel: 12,
        startNode: 'lighthouse_base',
        endNode: 'story_plaza',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_fountain_ring',
        unlockLevel: 13,
        startNode: 'growth_house_lv2',
        endNode: 'memory_fountain',
        pathType: 'stone',
        width: 6),
    PathConfig(
        id: 'path_plaza_library',
        unlockLevel: 14,
        startNode: 'story_plaza',
        endNode: 'library_seed',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_axis_2',
        unlockLevel: 15,
        startNode: 'memory_fountain',
        endNode: 'growth_clocktower',
        pathType: 'stone',
        width: 6),
    PathConfig(
        id: 'path_future_hill',
        unlockLevel: 16,
        startNode: 'growth_clocktower',
        endNode: 'lighthouse',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_social_loop',
        unlockLevel: 17,
        startNode: 'companion_plaza',
        endNode: 'harbor_pier',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_gallery',
        unlockLevel: 18,
        startNode: 'record_shed',
        endNode: 'memory_gallery',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_observatory',
        unlockLevel: 19,
        startNode: 'lighthouse',
        endNode: 'dream_observatory',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_world_complete',
        unlockLevel: 20,
        startNode: 'growth_academy',
        endNode: 'dream_observatory',
        pathType: 'gold',
        width: 6),
  ];

  static const anchors = <AnchorConfig>[
    AnchorConfig(
      id: 'anchor_starter',
      anchorBuildingId: 'starter_stone',
      visualWeight: 0.45,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_house',
      anchorBuildingId: 'growth_house',
      visualWeight: 0.70,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_house_upgraded',
      anchorBuildingId: 'growth_house_lv2',
      visualWeight: 0.78,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_fountain',
      anchorBuildingId: 'memory_fountain',
      visualWeight: 0.82,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_clocktower',
      anchorBuildingId: 'growth_clocktower',
      visualWeight: 0.88,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_lighthouse',
      anchorBuildingId: 'lighthouse',
      visualWeight: 0.90,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_academy',
      anchorBuildingId: 'growth_academy',
      visualWeight: 1.0,
      cameraFocus: true,
    ),
  ];

  static const levels = <IslandLevelConfig>[
    IslandLevelConfig(
        level: 1,
        islandRadius: 0.62,
        unlockZones: ['CenterZone'],
        unlockBuildings: [],
        unlockDecorations: const [],
        unlockPaths: [],
        unlockEffects: ['soft_breeze'],
        unlockWeather: 'clear',
        requiredGrowthScore: 0),
    IslandLevelConfig(
        level: 2,
        islandRadius: 0.64,
        unlockZones: [],
        unlockBuildings: [],
        unlockDecorations: const [],
        unlockPaths: ['path_center_seed'],
        unlockEffects: [],
        unlockWeather: 'clear',
        requiredGrowthScore: 100),
    IslandLevelConfig(
        level: 3,
        islandRadius: 0.66,
        unlockZones: ['MemoryZone'],
        unlockBuildings: ['starter_stone'],
        unlockDecorations: const [],
        unlockPaths: ['path_center_memory'],
        unlockEffects: ['leaf_float'],
        unlockWeather: 'clear',
        requiredGrowthScore: 250),
    IslandLevelConfig(
        level: 4,
        islandRadius: 0.68,
        unlockZones: [],
        unlockBuildings: [],
        unlockDecorations: const [],
        unlockPaths: ['path_memory_loop'],
        unlockEffects: [],
        unlockWeather: 'clear',
        requiredGrowthScore: 450),
    IslandLevelConfig(
        level: 5,
        islandRadius: 0.70,
        unlockZones: [],
        unlockBuildings: ['record_shed'],
        unlockDecorations: const [],
        unlockPaths: ['path_house_core'],
        unlockEffects: ['house_warm_light'],
        unlockWeather: 'clear',
        requiredGrowthScore: 700),
    IslandLevelConfig(
        level: 6,
        islandRadius: 0.73,
        unlockZones: ['HarborZone'],
        unlockBuildings: [],
        unlockDecorations: const [],
        unlockPaths: ['path_house_harbor'],
        unlockEffects: ['water_ripple'],
        unlockWeather: 'clear',
        requiredGrowthScore: 1100),
    IslandLevelConfig(
        level: 7,
        islandRadius: 0.76,
        unlockZones: ['EmotionZone'],
        unlockBuildings: ['memory_mailbox'],
        unlockDecorations: const [],
        unlockPaths: ['path_emotion_branch'],
        unlockEffects: ['wind_chime_glow'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 1600),
    IslandLevelConfig(
        level: 8,
        islandRadius: 0.79,
        unlockZones: [],
        unlockBuildings: [],
        unlockDecorations: const [],
        unlockPaths: ['path_flowerbed'],
        unlockEffects: ['petal_idle'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 2300),
    IslandLevelConfig(
        level: 9,
        islandRadius: 0.82,
        unlockZones: [],
        unlockBuildings: ['growth_house'],
        unlockDecorations: const [],
        unlockPaths: ['path_tent'],
        unlockEffects: ['firefly_idle'],
        unlockWeather: 'cloudy',
        requiredGrowthScore: 3200),
    IslandLevelConfig(
        level: 10,
        islandRadius: 0.85,
        unlockZones: [],
        unlockBuildings: [],
        unlockDecorations: const [],
        unlockPaths: ['path_ring_1'],
        unlockEffects: ['center_pulse'],
        unlockWeather: 'clear',
        requiredGrowthScore: 4500),
    IslandLevelConfig(
        level: 11,
        islandRadius: 0.88,
        unlockZones: ['KnowledgeZone'],
        unlockBuildings: ['harbor_pier', 'lighthouse_base'],
        unlockDecorations: const [],
        unlockPaths: ['path_center_knowledge'],
        unlockEffects: ['stream_shine'],
        unlockWeather: 'clear',
        requiredGrowthScore: 6200),
    IslandLevelConfig(
        level: 12,
        islandRadius: 0.91,
        unlockZones: [],
        unlockBuildings: ['story_plaza'],
        unlockDecorations: const [],
        unlockPaths: ['path_plaza_axis'],
        unlockEffects: ['plaza_spark'],
        unlockWeather: 'clear',
        requiredGrowthScore: 8500),
    IslandLevelConfig(
        level: 13,
        islandRadius: 0.94,
        unlockZones: [],
        unlockBuildings: ['emotion_windchime', 'memory_fountain'],
        unlockDecorations: const [],
        unlockPaths: ['path_fountain_ring'],
        unlockEffects: ['fountain_mist'],
        unlockWeather: 'clear',
        requiredGrowthScore: 11500),
    IslandLevelConfig(
        level: 14,
        islandRadius: 0.97,
        unlockZones: [],
        unlockBuildings: ['library_seed'],
        unlockDecorations: const [],
        unlockPaths: ['path_plaza_library'],
        unlockEffects: ['page_float'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 15500),
    IslandLevelConfig(
        level: 15,
        islandRadius: 1.00,
        unlockZones: [],
        unlockBuildings: ['habit_flowerbed', 'growth_clocktower'],
        unlockDecorations: const [],
        unlockPaths: ['path_axis_2'],
        unlockEffects: ['clock_light'],
        unlockWeather: 'clear',
        requiredGrowthScore: 20500),
    IslandLevelConfig(
        level: 16,
        islandRadius: 1.04,
        unlockZones: ['FutureZone'],
        unlockBuildings: ['lighthouse'],
        unlockDecorations: const [],
        unlockPaths: ['path_future_hill'],
        unlockEffects: ['lighthouse_beam'],
        unlockWeather: 'clear',
        requiredGrowthScore: 24500),
    IslandLevelConfig(
        level: 17,
        islandRadius: 1.08,
        unlockZones: [],
        unlockBuildings: ['quiet_tent', 'companion_plaza'],
        unlockDecorations: const [],
        unlockPaths: ['path_social_loop'],
        unlockEffects: ['life_idle'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 29000),
    IslandLevelConfig(
        level: 18,
        islandRadius: 1.12,
        unlockZones: [],
        unlockBuildings: ['memory_gallery'],
        unlockDecorations: const [],
        unlockPaths: ['path_gallery'],
        unlockEffects: ['gallery_glow'],
        unlockWeather: 'clear',
        requiredGrowthScore: 32000),
    IslandLevelConfig(
        level: 19,
        islandRadius: 1.16,
        unlockZones: [],
        unlockBuildings: ['dream_observatory'],
        unlockDecorations: const [],
        unlockPaths: ['path_observatory'],
        unlockEffects: ['future_glimmer'],
        unlockWeather: 'clear',
        requiredGrowthScore: 34000),
    IslandLevelConfig(
        level: 20,
        islandRadius: 1.20,
        unlockZones: [],
        unlockBuildings: ['growth_house_lv2', 'growth_academy'],
        unlockDecorations: const [],
        unlockPaths: ['path_world_complete'],
        unlockEffects: ['world_complete_aura'],
        unlockWeather: 'clear',
        requiredGrowthScore: 36000),
  ];

  static ZoneConfig? zoneById(String id) => _find(zones, id);
  static BuildingConfig? buildingById(String id) => _find(buildings, id);
  static PathConfig? pathById(String id) => _find(paths, id);

  static T? _find<T>(List<T> items, String id) {
    for (final item in items) {
      final value = switch (item) {
        ZoneConfig c => c.id,
        BuildingConfig c => c.id,
        PathConfig c => c.id,
        _ => '',
      };
      if (value == id) return item;
    }
    return null;
  }
}

class GrowthIslandConfigRepository {
  const GrowthIslandConfigRepository();

  IslandLevelConfig resolveLevel(int level) {
    final active = GrowthIslandConfigs.levels
        .where((config) => config.level <= level)
        .toList(growable: false);
    final current =
        active.isEmpty ? GrowthIslandConfigs.levels.first : active.last;
    return IslandLevelConfig(
      level: current.level,
      islandRadius: current.islandRadius,
      unlockZones: _merge(active.expand((config) => config.unlockZones)),
      unlockBuildings:
          _merge(active.expand((config) => config.unlockBuildings)),
      unlockDecorations: const [],
      unlockPaths: _merge(active.expand((config) => config.unlockPaths)),
      unlockEffects: _merge(active.expand((config) => config.unlockEffects)),
      unlockWeather: current.unlockWeather,
      requiredGrowthScore: current.requiredGrowthScore,
    );
  }

  List<ZoneConfig> resolveZones(List<String> ids) =>
      ids.map(GrowthIslandConfigs.zoneById).whereType<ZoneConfig>().toList();

  List<BuildingConfig> resolveBuildings(List<String> ids) => ids
      .map(GrowthIslandConfigs.buildingById)
      .whereType<BuildingConfig>()
      .toList();

  List<PathConfig> resolvePaths(List<String> ids) =>
      ids.map(GrowthIslandConfigs.pathById).whereType<PathConfig>().toList();

  List<String> _merge(Iterable<String> values) {
    final seen = <String>{};
    final out = <String>[];
    for (final value in values) {
      if (seen.add(value)) out.add(value);
    }
    return out;
  }
}
