workflows:
  Default Workflow:
    name: iOS Release IPA

    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: development
        bundle_identifier: com.xiaoerlcx.app

    scripts:
      - name: Build IPA
        script: |
          cd stday
          flutter pub get
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
          cd ..
          flutter build ipa --release

    artifacts:
      - stday/build/ios/ipa/*.ipa
