from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = "202606010001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("username", sa.String(64), nullable=False), sa.Column("email", sa.String(255), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True); op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table("roles", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("name", sa.String(64), nullable=False), sa.Column("description", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.PrimaryKeyConstraint("id")); op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table("permissions", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("code", sa.String(128), nullable=False), sa.Column("name", sa.String(64), nullable=False), sa.Column("description", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.PrimaryKeyConstraint("id")); op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_table("students", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("student_no", sa.String(64), nullable=False), sa.Column("name", sa.String(64), nullable=False), sa.Column("gender", sa.String(16)), sa.Column("birthday", sa.Date()), sa.Column("class_name", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_students_class_name"), "students", ["class_name"]); op.create_index(op.f("ix_students_name"), "students", ["name"]); op.create_index(op.f("ix_students_student_no"), "students", ["student_no"], unique=True)
    op.create_table("role_permissions", sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("permission_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("role_id", "permission_id"), sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permission"))
    op.create_table("user_roles", sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("user_id", "role_id"), sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"))
    op.create_table("observation_records", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("event_title", sa.String(128), nullable=False), sa.Column("event_content", sa.Text(), nullable=False), sa.Column("emotion_tag", sa.String(64)), sa.Column("growth_dimension", sa.String(64)), sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["created_by"], ["users.id"]), sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_observation_records_created_by"), "observation_records", ["created_by"]); op.create_index(op.f("ix_observation_records_event_type"), "observation_records", ["event_type"]); op.create_index(op.f("ix_observation_records_growth_dimension"), "observation_records", ["growth_dimension"]); op.create_index(op.f("ix_observation_records_student_id"), "observation_records", ["student_id"])

def downgrade() -> None:
    op.drop_index(op.f("ix_observation_records_student_id"), table_name="observation_records"); op.drop_index(op.f("ix_observation_records_growth_dimension"), table_name="observation_records"); op.drop_index(op.f("ix_observation_records_event_type"), table_name="observation_records"); op.drop_index(op.f("ix_observation_records_created_by"), table_name="observation_records"); op.drop_table("observation_records")
    op.drop_table("user_roles"); op.drop_table("role_permissions")
    op.drop_index(op.f("ix_students_student_no"), table_name="students"); op.drop_index(op.f("ix_students_name"), table_name="students"); op.drop_index(op.f("ix_students_class_name"), table_name="students"); op.drop_table("students")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions"); op.drop_table("permissions")
    op.drop_index(op.f("ix_roles_name"), table_name="roles"); op.drop_table("roles")
    op.drop_index(op.f("ix_users_username"), table_name="users"); op.drop_index(op.f("ix_users_email"), table_name="users"); op.drop_table("users")
